### ISSUE TITLE
birdwatcher randomly crashes

### ISSUE THREAD

**Issue by tchadelicard** [alice-lg/birdwatcher#14]
-- Logs begin at Sat 2019-12-28 09:50:05 CET. --
déc. 28 18:06:45 edge1 birdwatcher[12824]: panic: interface conversion: interface {} is nil, not string
déc. 28 18:06:45 edge1 birdwatcher[12824]: goroutine 33 [running]:
déc. 28 18:06:45 edge1 birdwatcher[12824]: github.com/alice-lg/birdwatcher/bird.parseRouteLines(0xc000166400, 0x12, 0x20, 0x3, 0xc00005e180)
déc. 28 18:06:45 edge1 birdwatcher[12824]:         /root/go/src/github.com/alice-lg/birdwatcher/bird/parser.go:329 +0xf4c
déc. 28 18:06:45 edge1 birdwatcher[12824]: github.com/alice-lg/birdwatcher/bird.workerForRouteBlockParsing(0xc00005e120, 0xc00005e180, 0xc00007a000)
déc. 28 18:06:45 edge1 birdwatcher[12824]:         /root/go/src/github.com/alice-lg/birdwatcher/bird/parser.go:307 +0x73
déc. 28 18:06:45 edge1 birdwatcher[12824]: created by github.com/alice-lg/birdwatcher/bird.startRouteWorkers.func1
déc. 28 18:06:45 edge1 birdwatcher[12824]:         /root/go/src/github.com/alice-lg/birdwatcher/bird/parser.go:265 +0x60
déc. 28 18:06:45 edge1 systemd[1]: birdwatcher4.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
déc. 28 18:06:45 edge1 systemd[1]: birdwatcher4.service: Failed with result 'exit-code'.

**Comment by petabyteboy** [comment]
Hello, did you find a solution to this problem, I'm having the same issue.

**Comment by petabyteboy** [comment]
FYI this is fixed by following the README instructions on setting the correct timestamp format
