### ISSUE TITLE
Clarify support for Bird v2.0

### ISSUE THREAD

**Issue by stv0g** [alice-lg/birdwatcher#16]
Does birdwatcher support both Bird v1 and v2?

I am a bit confused. The README does not mention it.. Same for the alice-lg frontend.
Seems like the IX users DECIX and ECIX are both running Bird v1.6.3

**Comment by vidister** [comment]
BCIX is running Bird v2:
https://lg.bcix.de/

**Comment by stv0g** [comment]
@vidister Thanks for the hint! Do you know if they run two instances of birdwatcher to monitor a single Bird instance? Or do they have independent Bird instances for v4/v6?

**Comment by stv0g** [comment]
I figured it out:

For Bird 2.x, you have to run a single Bird instance and two separate instance of birdwatcher

**Comment by netstx** [comment]
> I figured it out:
> 
> For Bird 2.x, you have to run a single Bird instance and two separate instance of birdwatcher

I've done this (two birdwatcher instances (v4 and v6)), but for some reason birdwatcher will not listen on the v6 instance... Do you mind sharing your config or systemd services?
