### ISSUE TITLE
"protocols" endpoint doesn't show routes count for IPv6 protocol on BIRDv2 

### ISSUE THREAD

**Issue by nstgt** [alice-lg/birdwatcher#22]
Hi, 

I found an issue that current birdwatcher can't parse "protocol" for BIRDv2 which run with both IPv4 and IPv6. When I curl to `/protocols/bgp`, then I could get routes count for IPv4 protocol but couldn't get it for IPv6 like follows:

```
{
    ...
    "protocols": {
        "B2001_db8__101": {
            "af_announced": "ipv6",
            "bgp_state": "Established",
            "bird_protocol": "BGP",
            "connection": "Established",
            "description": "TEST_PEER_1",
            "hold_timer": "73.180/90",
            "keepalive_timer": "1.859/30",
            "local_as": 65100,
            "neighbor_address": "2001:db8::101",
            "neighbor_as": 65001,
            "neighbor_id": "10.0.0.101",
            "protocol": "B2001_db8__101",
            "route_changes": {},
            "routes": {
                "accepted": 0,
                "exported": 0,
                "filtered": 0,
                "imported": 0,
                "preferred": 0
            },
            "session": "external route-server AS4",
            "source_address": "2001:db8:7:1::211",
            "state": "up",
            "state_changed": "2020-02-23 18:37:40",
            "table": "---"
        }
    }
}
```

https://github.com/alice-lg/birdwatcher/blob/master/bird/parser.go#L539
To my understanding, this line cause the issue.
The function `isCorrectChannel()` always returns false while parsing lines following `"Channel ipv6"` in result of `show protocols all B2001_db8__101`, because `bird.IPVersion` is set as `"4"`.

**Comment by stv0g** [comment]
Hi @nstgt,

did you start birdwatcher with the `-6` option?

Its currently to be expected that you need to run two instances of birdwatcher.
One for IPv4 and another one for IPv6

**Comment by stv0g** [comment]
See also #16

**Comment by nstgt** [comment]
@stv0g 
Thank you for your comments. I understand current usage of birdwather for BIRDv2 v4/v6.
Let me close this issue.

Just FYI, I made a small patch to run single birdwather for BIRDv2. 
(I know this is ugly and may cause other issue..)
https://github.com/mfeed/birdwatcher/commit/423bce7a3baf143425333e2ca9ceedc9a07c0941
