### ISSUE TITLE
Deprecation of 'go get' for installing executables

### ISSUE THREAD

**Issue by Mr-Sheep** [alice-lg/birdwatcher#42]
The command `go get github.com/alice-lg/birdwatcher` in README is now deprecated as stated in [Deprecation of 'go get' for installing executables](https://golang.org/doc/go-get-install-deprecation).

Please consider changing it to `go install github.com/alice-lg/birdwatcher@latest`

**Comment by annikahannig** [comment]
:+1: 
updated the readme
