### ISSUE TITLE
undefined: sync.Map

### ISSUE THREAD

**Issue by maximiliandallmair** [alice-lg/birdwatcher#7]
go get github.com/alice-lg/birdwatcher
# github.com/alice-lg/birdwatcher/bird
go/src/github.com/alice-lg/birdwatcher/bird/bird.go:31: undefined: sync.Map

how can i fix this? any software missing?

**Comment by maximiliandallmair** [comment]
help

**Comment by mhannig** [comment]
Hey! Good morning! :)

Just saw this issue.
I'll look into why the `go get` method is not working.

For the time beeing, can you try building it by cloning the repo and running `make`?

**Comment by maximiliandallmair** [comment]
make linux
GOARCH=amd64 GOOS=linux go build -o birdwatcher-linux-amd64
# github.com/alice-lg/birdwatcher/bird
../go/src/github.com/alice-lg/birdwatcher/bird/bird.go:31: undefined: sync.Map
Makefile:37: recipe for target 'linux' failed
make: *** [linux] Error 2

same with make

**Comment by mhannig** [comment]
Okay, which go version do you have?

**Comment by maximiliandallmair** [comment]
go version go1.7.4 linux/amd64

**Comment by mhannig** [comment]
Looks like at least `1.9` is required.

**Comment by mhannig** [comment]
(I'll make a note in the readme :slightly_smiling_face: )
